//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Criteria()
        {
            this.Experts_comments = new HashSet<Experts_comments>();
        }
    
        public int id { get; set; }
        public string full_name { get; set; }
        public string short_name { get; set; }
        public string document_name { get; set; }
        public int group_id { get; set; }
        public int type_organization { get; set; }
        public int coefficient_id { get; set; }
    
        public virtual Coefficients Coefficients { get; set; }
        public virtual Groups Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Experts_comments> Experts_comments { get; set; }
    }
}
