//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class curators_and_controlers
    {
        public int id { get; set; }
        public int curator_id { get; set; }
        public int education_institution_id { get; set; }
    
        public virtual education__institution education__institution { get; set; }
        public virtual User User { get; set; }
    }
}
