//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experts_comments
    {
        public int id { get; set; }
        public int site_experts_id { get; set; }
        public int answer { get; set; }
        public string comment { get; set; }
        public int criteria_id { get; set; }
    
        public virtual Criteria Criteria { get; set; }
        public virtual site_experts site_experts { get; set; }
    }
}
