//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class experts_ratinng
    {
        public int id { get; set; }
        public int monitoring_id { get; set; }
        public int audit_object_id { get; set; }
        public int sum { get; set; }
    
        public virtual audit_object audit_object { get; set; }
        public virtual monitoring monitoring { get; set; }
    }
}
