//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_event
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> kind_event_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string IP_adress_object { get; set; }
    
        public virtual kind_event kind_event { get; set; }
        public virtual User User { get; set; }
    }
}
