//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MonitoringEntities : DbContext
    {
        public MonitoringEntities()
            : base("name=MonitoringEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<area> area { get; set; }
        public virtual DbSet<audit_object> audit_object { get; set; }
        public virtual DbSet<Coefficients> Coefficients { get; set; }
        public virtual DbSet<Criteria> Criteria { get; set; }
        public virtual DbSet<curators_and_controlers> curators_and_controlers { get; set; }
        public virtual DbSet<department_subordination> department_subordination { get; set; }
        public virtual DbSet<district> district { get; set; }
        public virtual DbSet<education__institution> education__institution { get; set; }
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<experts> experts { get; set; }
        public virtual DbSet<Experts_comments> Experts_comments { get; set; }
        public virtual DbSet<experts_ratinng> experts_ratinng { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<kind_edu> kind_edu { get; set; }
        public virtual DbSet<kind_event> kind_event { get; set; }
        public virtual DbSet<log_event> log_event { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<monitoring> monitoring { get; set; }
        public virtual DbSet<ownership_type> ownership_type { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<rating_attendance> rating_attendance { get; set; }
        public virtual DbSet<reviews_user> reviews_user { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<site_experts> site_experts { get; set; }
        public virtual DbSet<state_edu> state_edu { get; set; }
        public virtual DbSet<state_reviews> state_reviews { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<system_event_state> system_event_state { get; set; }
        public virtual DbSet<system_events> system_events { get; set; }
        public virtual DbSet<technical_rating> technical_rating { get; set; }
        public virtual DbSet<type_edu> type_edu { get; set; }
        public virtual DbSet<type_education_institution> type_education_institution { get; set; }
        public virtual DbSet<type_reviews> type_reviews { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<users_rating> users_rating { get; set; }
        public virtual DbSet<users_state> users_state { get; set; }
    }
}
