//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviews_user
    {
        public int id { get; set; }
        public string title { get; set; }
        public string text { get; set; }
        public string author_name { get; set; }
        public string author_email { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public int state_id { get; set; }
        public string curator_answer { get; set; }
        public int type_id { get; set; }
        public int audit_object_id { get; set; }
    
        public virtual audit_object audit_object { get; set; }
        public virtual state_reviews state_reviews { get; set; }
        public virtual type_reviews type_reviews { get; set; }
    }
}
