//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_experts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public site_experts()
        {
            this.Experts_comments = new HashSet<Experts_comments>();
        }
    
        public int id { get; set; }
        public int audit_object_id { get; set; }
        public int expert_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> monitoring_id { get; set; }
    
        public virtual audit_object audit_object { get; set; }
        public virtual experts experts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Experts_comments> Experts_comments { get; set; }
        public virtual monitoring monitoring { get; set; }
    }
}
