//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class technical_rating
    {
        public int id { get; set; }
        public int audit_object_id { get; set; }
        public Nullable<decimal> site_accessibility { get; set; }
        public string status_code { get; set; }
        public string using_HTTPS { get; set; }
        public Nullable<decimal> response_time { get; set; }
        public string robots_txt { get; set; }
        public Nullable<decimal> full_load { get; set; }
        public Nullable<int> sum { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string img_title { get; set; }
        public string has_title { get; set; }
        public string w3c { get; set; }
        public Nullable<int> broken_links_count { get; set; }
        public string broken_links_text { get; set; }
        public string site_map { get; set; }
        public string site_map_ok { get; set; }
        public int monitoring_id { get; set; }
        public Nullable<int> nesting_level { get; set; }
    
        public virtual audit_object audit_object { get; set; }
        public virtual monitoring monitoring { get; set; }
    }
}
