//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_rating
    {
        public int id { get; set; }
        public int audit_object_id { get; set; }
        public Nullable<int> number_reviews { get; set; }
        public Nullable<int> number_processed_reviews { get; set; }
        public Nullable<int> number_likes { get; set; }
        public Nullable<int> sum { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual audit_object audit_object { get; set; }
    }
}
